/* ERP_1 database roles — idempotent */
USE [ERP_1];
GO

IF DATABASE_PRINCIPAL_ID('ERP_AppRead') IS NULL
    CREATE ROLE [ERP_AppRead];
IF DATABASE_PRINCIPAL_ID('ERP_AppWrite') IS NULL
    CREATE ROLE [ERP_AppWrite];
IF DATABASE_PRINCIPAL_ID('ERP_AppAdmin') IS NULL
    CREATE ROLE [ERP_AppAdmin];
GO

GRANT SELECT TO [ERP_AppRead];
GRANT SELECT, INSERT, UPDATE, DELETE TO [ERP_AppWrite];
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE TO [ERP_AppAdmin];
GO

PRINT 'ERP_AppRead / ERP_AppWrite / ERP_AppAdmin roles ready.';
PRINT 'Next: 02_CreateDB_Roles.sql';
GO
