 --09 fill some Quotes from HPAlloy to ERP_1 for testing

    SET IDENTITY_INSERT [ERP_2].[dbo].[AllQuotes] ON;
    INSERT INTO [ERP_2].[dbo].[AllQuotes]
        ([Company]
      ,[Name]
      ,[Phone]
      ,[Phone_Ext]
      ,[Fax]
      ,[Email]
      ,[PO_num]
      ,[Alloy]
      ,[Form]
      ,[CC]
      ,[CL]
      ,[Pieces]
      ,[Thck]
      ,[Sz2]
      ,[Sz3]
      ,[Weight]
      ,[Descript]
      ,[p_lb]
      ,[p_pc]
      ,[p_ft]
      ,[Cuts]
      ,[OtherFld]
      ,[OtherP]
      ,[LotP]
      ,[LotCost]
      ,[LeadTime]
      ,[cWeight]
      ,[cP_lb]
      ,[cP_pc]
      ,[cP_pcc]
      ,[cthk]
      ,[cLotP]
      ,[cLotcP]
      ,[cCut]
      ,[cCutM]
      ,[cKerfD]
      ,[InqDate]
      ,[InqNum]
      ,[InqNumP]
      ,[SalesP]
      ,[SalesNum]
      ,[SOitem]
      ,[item]
      ,[HPApo]
      ,[POitem]
      ,[SaleDate]
      ,[ShipDate]
      ,[Buyfrom]
      ,[BuyCost]
      ,[BuyFrom2]
      ,[HPApo2]
      ,[open_]
      ,[Bracket]
      ,[CustID]
      ,[QuoteMemo]
      ,[Comments]
      ,[CountryC]
      ,[Country]
      ,[Services]
      ,[RandLen]
      ,[Metric]
      ,[StartStock]
      ,[TN]
      ,[sz1orig]
      ,[sz2orig]
      ,[sz3orig]
      ,[QuoteDate]
      ,[Cover]
      ,[Cut]
      ,[ID]
      ,[Line1]
      ,[WO]
      ,[CutOptions]
      ,[Surcharge]
      ,[Regret]
      ,[NoNoiseName]
      ,[CutHr]
      ,[Q_P]
      ,[Q_QTY]
      ,[Q_PU]
      ,[Q_Total]
      ,[S_QTY]
      ,[S_P]
      ,[S_PU]
      ,[S_Total]
      ,[StandardSize]
      ,[CustDisc]
      )
    SELECT TOP (100) 
       [Company]
      ,[Name]
      ,[Phone]
      ,[Phone_Ext]
      ,[Fax]
      ,[Email]
      ,[PO_num]
      ,[Alloy]
      ,[Form]
      ,[CC]
      ,[CL]
      ,[Pieces]
      ,[Thck]
      ,[Sz2]
      ,[Sz3]
      ,[Weight]
      ,[Descript]
      ,[p_lb]
      ,[p_pc]
      ,[p_ft]
      ,[Cuts]
      ,[OtherFld]
      ,[OtherP]
      ,[LotP]
      ,[LotCost]
      ,[LeadTime]
      ,[cWeight]
      ,[cP_lb]
      ,[cP_pc]
      ,[cP_pcc]
      ,[cthk]
      ,[cLotP]
      ,[cLotcP]
      ,[cCut]
      ,[cCutM]
      ,[cKerfD]
      ,[InqDate]
      ,[InqNum]
      ,[InqNumP]
      ,[SalesP]
      ,[SalesNum]
      ,[SOitem]
      ,[item]
      ,[HPApo]
      ,[POitem]
      ,[SaleDate]
      ,[ShipDate]
      ,[Buyfrom]
      ,[BuyCost]
      ,[BuyFrom2]
      ,[HPApo2]
      ,[open_]
      ,[Bracket]
      ,[CustID]
      ,[QuoteMemo]
      ,[Comments]
      ,[CountryC]
      ,[Country]
      ,[Services]
      ,[RandLen]
      ,[Metric]
      ,[StartStock]
      ,[TN]
      ,[sz1orig]
      ,[sz2orig]
      ,[sz3orig]
      ,[QuoteDate]
      ,[Cover]
      ,[Cut]
      ,[ID]
      ,[Line1]
      ,[WO]
      ,[CutOptions]
      ,[Surcharge]
      ,[Regret]
      ,[NoNoiseName]
      ,[CutHr]
      ,[Q_P]
      ,[Q_QTY]
      ,[Q_PU]
      ,[Q_Total]
      ,[S_QTY]
      ,[S_P]
      ,[S_PU]
      ,[S_Total]
      ,[StandardSize]
      ,[CustDisc]
    FROM    [HPAlloy].[dbo].[AllQuotes]
    WHERE SalesP = 'D'
    ORDER BY InqDate DESC;
    SET IDENTITY_INSERT [ERP_2].[dbo].[AllQuotes] OFF;
    PRINT 'Copied AllQuotes: ' + CAST(@@ROWCOUNT AS VARCHAR(10)) + ' rows';


    --QuickCompany 
    INSERT INTO [ERP_2].[dbo].[QuickCompany] (
    [customer]
      ,[company]
      ,[name]
      ,[countryc]
      ,[phone]
      ,[phone_ext]
      ,[fax]
      ,[email]
      ,[xcomp]
      ,[xCompName]
      ,[status]
      ,[home]
      ,[car]
      ,[notes]
      ,[PU]
      ,[LastEdit]
      ,[NoNoiseName]
      
    )
    SELECT [QC].[customer]
      ,[QC].[company]
      ,[QC].[name]
      ,[QC].[countryc]
      ,[QC].[phone]
      ,[QC].[phone_ext]
      ,[QC].[fax]
      ,[QC].[email]
      ,[QC].[xcomp]
      ,[QC].[xCompName]
      ,[QC].[status]
      ,[QC].[home]
      ,[QC].[car]
      ,[QC].[notes]
      ,[QC].[PU]
      ,[QC].[LastEdit]
      ,[QC].[NoNoiseName]
      
  FROM [HPAlloy].[dbo].[QuickCompany] QC
WHERE QC.customer IN (SELECT Distinct CustID FROM [ERP_2].[dbo].[AllQuotes] WHERE LEN(CustID)> 0 AND CustID <> '0' AND CustID IS NOT NULL);

    PRINT 'Copied QuickCompany: ' + CAST(@@ROWCOUNT AS VARCHAR(10)) + ' rows';
    --

--
INSERT INTO [ERP_2].[dbo].[Quote_No] ([Inqnum]
      ,[InqNumP]
      ,[SalesP]
      ,[revision]
      ,[InitDate]
      ,[ExpireDate]
      ,[ProdReqDefine]
      ,[DiffResolved]
      ,[HPAcapable]
      ,[Comments]
      ,[Contents]
      ,[AllInqNum]
      ,[LastEdit]
      ,[AllQuotes_IDs]
        )
SELECT [Inqnum]
      ,[InqNumP]
      ,[SalesP]
      ,[revision]
      ,[InitDate]
      ,[ExpireDate]
      ,[ProdReqDefine]
      ,[DiffResolved]
      ,[HPAcapable]
      ,[Comments]
      ,[Contents]
      ,[AllInqNum]
      ,[LastEdit]
      ,[AllQuotes_IDs]
      FROM [HPAlloy].[dbo].[Quote_No]
WHERE InqNumP IN (SELECT Distinct InqNumP FROM [ERP_2].[dbo].[AllQuotes] WHERE LEN(InqNumP)> 0 AND InqNumP <> '0' AND InqNumP IS NOT NULL);

    PRINT 'Copied Quotes_No: ' + CAST(@@ROWCOUNT AS VARCHAR(10)) + ' rows';


--
DELETE FROM [ERP_2].[dbo].[Sources];

SET IDENTITY_INSERT [ERP_2].[dbo].[Sources] ON;
INSERT INTO [ERP_2].[dbo].[Sources]
([Company]
      ,[Alloy_AKA]
      ,[Alloy]
      ,[alloy_num]
      ,[UNS]
      ,[Spec]
      ,[f10]
      ,[f20]
      ,[f30]
      ,[f40]
      ,[f60]
      ,[f65]
      ,[f70]
      ,[f75]
      ,[Notes]
      ,[Stk]
      ,[MK]
      ,[ID]
      ,[ID_Sources]
      ,[VendCode])
SELECT [Company]
      ,[Alloy_AKA]
      ,[Alloy]
      ,[alloy_num]
      ,[UNS]
      ,[Spec]
      ,[f10]
      ,[f20]
      ,[f30]
      ,[f40]
      ,[f60]
      ,[f65]
      ,[f70]
      ,[f75]
      ,[Notes]
      ,[Stk]
      ,[MK]
      ,[ID]
      ,[ID_Sources]
      ,[VendCode]
  FROM [HPAlloy].[dbo].[Sources]
    SET IDENTITY_INSERT [ERP_2].[dbo].[Sources] OFF;
    PRINT 'Copied Sources: ' + CAST(@@ROWCOUNT AS VARCHAR(10)) + ' rows';


--
SET IDENTITY_INSERT [ERP_2].[dbo].[SourcePH] ON;
INSERT INTO [ERP_2].[dbo].[SourcePH]
([company]
      ,[phone]
      ,[fax]
      ,[person]
      ,[email]
      ,[email2]
      ,[ID]
      ,[InActive]
      ,[VendCode]
      ,[ContactID]
      )
SELECT [company]
      ,[phone]
      ,[fax]
      ,[person]
      ,[email]
      ,[email2]
      ,[ID]
      ,[InActive]
      ,[VendCode]
      ,[ContactID]
  FROM [HPAlloy].[dbo].[SourcePH]
    SET IDENTITY_INSERT [ERP_2].[dbo].[SourcePH] OFF;
    PRINT 'Copied SourcePH: ' + CAST(@@ROWCOUNT AS VARCHAR(10)) + ' rows';
